# -*- coding: utf-8 -*-
"""K-means Clustering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_KYbh4ZKLkNiFjHKbkRrZy2UBuPxOEw4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Mall_Customers.csv')

df.head()

x = df.iloc[:,3:5].values

from sklearn.cluster import KMeans
wcss = []
for i in range(1,11):
  cluster = KMeans(n_clusters=i,init = 'k-means++',random_state=42)
  cluster.fit(x)
  wcss.append(cluster.inertia_)
plt.plot(range(1,11),wcss)
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

Kmeans = KMeans(n_clusters=5,init = 'k-means++',random_state=42)
y_pred = Kmeans.fit_predict(x)

y_pred

from matplotlib.colors import ListedColormap
unique_cluster = np.unique(y_pred)
for i in range(len(unique_cluster)):
  labels = unique_cluster[i]
  indices = np.where(y_pred == labels)
  x_values = x[indices,0]
  y_values = x[indices,1]
  plt.scatter(x_values,y_values,label = labels,s = 100)